### ISSUE TITLE
Would like have a better friendly style of LoadingSpinner

### ISSUE THREAD

**Issue by Quineone** [basics/nuxt-booster#651]
**Describe the bug**
Instead of set the loading spinner for img tag
```css
.${this.className}.loading {
  background-image: url(${this.#dataUri});
  background-repeat: no-repeat;
  background-position: center;
  background-size: ${this.#size};
  background-color: ${this.#backgroundColor};
 }
```
![image](https://user-images.githubusercontent.com/15320933/177911025-f40ad744-1133-4064-a2e4-0a43043f0f45.png)

would like to set this for the img's pseudo-elements  :before or :after 
```css
.${this.className}.loading:after {
  background-image: url(${this.#dataUri});
  background-repeat: no-repeat;
  background-position: center;
  background-size: ${this.#size};
  background-color: ${this.#backgroundColor};
  content: '';
  display: block;
  position: absolute;
  z-index: 2;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
 }
```
![image](https://user-images.githubusercontent.com/15320933/177910967-d91ffb02-d36f-4d08-9d3a-9e0cd9920388.png)
